### ISSUE TITLE
En los subs: El boton Seguir/Siguiendo no muestra el estado correcto

### ISSUE THREAD

**Issue by castarco** [gallir/Meneame#108]
Hola,

en los subs, hay un panel derecho con el título del sub, el número de seguidores y un botón que puede mostrar los textos "Seguir" o "Siguiendo".

Se entiende que, si estoy siguiendo el sub, el texto que debería mostrar es "Siguiendo", o "Seguir" en caso contrario. Pues parece que, aun estando siguiendo los subs, cuando entro, el texto que aparece es "Seguir", lo cual no es correcto.

Si hago click un par de veces sobre él, entonces el texto se corrige, pero seguramente porque he cambiado el estado dos veces. Esto puede ser problemático porque los usuarios pueden dejar de seguir accidentalmente algunos subs por el hecho de que no les cuadre el texto del botón, y hagan click sobre él.

**Comment by eusonlito** [comment]
Gracias, subiremos la corrección lo antes posible :+1:
