### ISSUE TITLE
Facebook login?

### ISSUE THREAD

**Issue by osvid** [gallir/Meneame#114]
Hola, sobre la base del código de MNM he montado una plataforma de publicación literaria en http://poemame.com. 

Hace unas semanas observé que el login con Facebook había dejado de funcionar, tanto en MNM como en mi plataforma. 

He visto que en MNM en producción ya funciona de nuevo, pero no así en el código del repositorio ¿Podríais pf subir el parche en github, o pasarme el código que lo resuelve? 

Gracias, un saludo!

**Comment by felixgomez** [comment]
Hola @osvid, interesante proyecto. Efectivamente, el login de Facebook había dejado de funcionar y por ello y aprovechando que hemos empezado a gestionar las dependencias a través de `composer` hemos incorporado la última versión del sdk oficial de facebook y reescrito `www/oauth/fbconnect.php` para hacer uso de él.

**Comment by osvid** [comment]
Hola @felixgomez. Gracias. Esencialmente es un MNM configurado como plataforma de blogging y en el que he cambiado el diseño y "capado" funcionalidades de MNM que no eran de utilidad (o que despistaban a los usuarios). Para el login estuve mirando también utilizar la versión del sdk (supuse que era un problema de obsolescencia del sdk anterior, que ya tenía unos años) pero no llegué a integrarlo. Voy a echar un vistazo a vuestra implementación. Gracias de nuevo, un saludo!
