### ISSUE TITLE
Problema lectura RSS

### ISSUE THREAD

**Issue by profesors** [gallir/Meneame#115]
Empleando un lector de RSS para leer los artículos de menéame y veo que la codificación de caracteres es incorrecta. (Sólo ocurre con los artículos). Ejemplo (C&P):

"La anÃcdota favorita de todos los gafotas, que puede que sea apÃcrifa, es la de cuando DiÃgenes se encontrÃ con Alejandro Magno."

I use a RSS feed reader to read the articles of meneame and I have found a problem in the characters codifications as in the example above.

**Comment by profesors** [comment]
Tiene pinta de que tiene que ver con algo de UTF-8, quizá.

**Comment by keymon** [comment]
Lo mismo pasa con http://feedly.com/

**Comment by Nemrac** [comment]
ya arreglaron el bug, probad con los nuevos artículos/meneos  que salgan

**Comment by nosuko** [comment]
Arreglaron el bug pero no subieron el código. Como siempre. El último commit de octubre de 2017...

**Comment by Nemrac** [comment]
Como siempre, no lees. Lo ha de autorizar Gallir que es su github (ya está solicitada autorización, en cuanto la tengan los programadores se subirán con más rapidez)

La paciencia es una virtud.

**Comment by eusonlito** [comment]
Efectivamente hemos solicitado a Ricardo los permisos para poder actualizar el repositorio, y a continuación en cuanto se pueda, realizar la migración como organización.

Está explicado en esta nota https://www.meneame.net/notame/3028946

Sé que desde octubre hasta ahora es mucho tiempo, pero por desgracia la pelota no está en nuestro tejado para poder agilizarlo más.

**Comment by muzzol** [comment]
**Podríamos hacer un fork y listo, pero no queremos hacer algo en plan chapuza para salir del apuro.**

esto es lo que no tiene mucho sentido para mi. que problema hay en hacer un fork hasta que tengais acceso al repo original?
si es por un tema de imagen creo que estais quedando mucho peor con la sensación de dejadez del código. que mas da que sea un fork cuando github facilita todo el proceso justamente para evitar casos como este?

quien haya llegado a la conclusión que utilizar los recursos de github es una chapuza no debe ser developer o prioriza otros aspectos.

**Comment by eusonlito** [comment]
Lo que tú digas, "developer".

**Comment by muzzol** [comment]
wow!
comentario top :)

**Comment by eusonlito** [comment]
Es para intentar mantener el nivel, pero me lo estáis poniendo muy difícil!

**Comment by eusonlito** [comment]
Solved!
