### ISSUE TITLE
meneame.sql

### ISSUE THREAD

**Issue by otrascampanas** [gallir/Meneame#116]
Hola!

Antes que nada les agradezco por haber publicado el proyecto. 

Quisiera saber si los scripts sql están actualizados, ya que estoy intentando correr el proyecto en mi propio servidor y continuamente me encuentro con errores del tipo

 `"Unknown column 'xxxx' in"` 
 `"Field 'some_fild' doesn't have a default value"`
 `"Table 'meneame.sometable' doesn't exist"`

y cosas por el estilo.

¿Alguna recomendación?

Gracias de antemano.

**Comment by eusonlito** [comment]
Estás añadiendo todos los SQL del directorio `sql` en orden?

**Comment by eusonlito** [comment]
No, prueba únicamente con `meneame.sql` y después las que contienen la fecha por ese orden. `categories.sql` y `subs.sql` ya deberían estar integradas en `meneame.sql`
