### ISSUE TITLE
Sugerencia para el uso de SQL

### ISSUE THREAD

**Issue by Tasiobg** [gallir/Meneame#118]
No sabia que meneame estaba haciendo "Developing in the Open", asi que he echado un vistazo rapido por curiosidad y me ha llamado la atención esta linea:
https://github.com/gallir/Meneame/blob/3a956b75b0f1743803a058b620b2c750734767aa/www/libs/mafia.php#L132

Solo comentar que es buena practica usar "prepared statements" siempre que sea posible, de esta forma prevenis vulnerabilidades y manteneis buenas practicas en el código.

Suerte.

**Comment by eusonlito** [comment]
Hola! no acabo de entenderlo :)

Esa variable ya viene sanitizada previamente, con lo cual su uso en ese punto es seguro:

https://github.com/gallir/Meneame/blob/3a956b75b0f1743803a058b620b2c750734767aa/www/libs/mafia.php#L150

No habría posibilidades de colar nada no seguro en esa variable que pueda generar ninguna vulnerabilidad.

Saludos!
