### ISSUE TITLE
Autenticación con Twitter no funciona

### ISSUE THREAD

**Issue by osvid** [gallir/Meneame#122]
Hola, la autenticación con Twitter no funciona. Genera el siguiente error: error de conexión a twitter (authRequest) 

También lo he detectado en mi proyecto http://poemame.com. 

Un saludo,
Oscar D.

**Comment by eusonlito** [comment]
Gracias! Es para nuevos perfiles, o sólo para autenticación de usuarios ya registrados?

**Comment by osvid** [comment]
Falla en ambos casos. He probado (por si acaso) a regenerar las claves de la app pero como era de esperar no funciona. 

Entiendo que lo que ocurre es que la función authRequest() arroja una excepción.

**Comment by eusonlito** [comment]
Exacto, ya lo veo, voy revisar el problema.

Gracias!

**Comment by osvid** [comment]
¿Puede que tenga algo que ver con la declaración de la callback URLs? 

https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342
https://twittercommunity.com/t/testing-out-callback-url-whitelisting-ahead-of-launch/106859

_Starting June 12th, 2018, we will require that any callback URL used with this endpoint will have to be whitelisted within the app settings on apps.twitter.com_

¿Cómo lo tenéis configurado en Menéame?

Gracias!
OD

**Comment by eusonlito** [comment]
Listo! Gracias!
