### ISSUE TITLE
Permitir cambiar el voto

### ISSUE THREAD

**Issue by Aokromes** [gallir/Meneame#30]
Con la llegada de los dispositivos moviles/tactiles mucha gente vota positivo o negativo por error a los comentarios, estaria bien permitir cambiar el voto o incluso retirarlo completamente.
Tambien estaria bien permitir cambiar el voto de la noticia (para cuando una noticia se vota duplicada por error por ejemplo)

**Comment by eusonlito** [comment]
Done!
