### ISSUE TITLE
mas tipos de votos a comentarios

### ISSUE THREAD

**Issue by Aokromes** [gallir/Meneame#39]
Estaria bien tener al menos una opcion mas de votos para los comentarios, ya que la gente suele usar el voto negativo para cualquier cosa, estaria bien tener un voto "erroneo" para cometarios erroneos. o tal vez cambiar el voto negativo para votar comentarios erroneos etc y otro para reportar spam, insultos, etc.

**Comment by branigan** [comment]
Al hilo de esto yo propondría permitir “tagear” comentarios como ¿broma? Y que en los filtros se pueda seleccionar eliminando los Que tengan esta etiqueta.

Últimamente se hace difícil leer comentarios interesantes entre tanto chascarrillo y su correspondientes respuestas (porque aunque filtres por karma o votos siguen saliendo las bromas)
